// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEwFYc8POLiAjuZuVB7313PN-iKpGQxKE',
    appId: '1:738009573337:web:c5577f8c826c55c06cdbc8',
    messagingSenderId: '738009573337',
    projectId: 'notify-test-flutter-project',
    authDomain: 'notify-test-flutter-project.firebaseapp.com',
    storageBucket: 'notify-test-flutter-project.appspot.com',
    measurementId: 'G-0RZPBKEHDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZDABwPgX7NR_snXjFtgPWlwym2U6BPmY',
    appId: '1:738009573337:android:0f47cb0b4bc5dbbe6cdbc8',
    messagingSenderId: '738009573337',
    projectId: 'notify-test-flutter-project',
    storageBucket: 'notify-test-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF4kVmB2Effy_xs56rnHiebmtGwjE0ILk',
    appId: '1:738009573337:ios:359fac27bbb164526cdbc8',
    messagingSenderId: '738009573337',
    projectId: 'notify-test-flutter-project',
    storageBucket: 'notify-test-flutter-project.appspot.com',
    iosBundleId: 'com.example.mealFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF4kVmB2Effy_xs56rnHiebmtGwjE0ILk',
    appId: '1:738009573337:ios:f029b79a1b53bdd06cdbc8',
    messagingSenderId: '738009573337',
    projectId: 'notify-test-flutter-project',
    storageBucket: 'notify-test-flutter-project.appspot.com',
    iosBundleId: 'com.example.mealFinder.RunnerTests',
  );
}
